"""Adiciona modelo Filme e relação com Episodio

Revision ID: 1c3bf387d703
Revises: 
Create Date: 2025-07-31 02:16:46.321272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3bf387d703'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filme_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'filme', ['filme_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('filme_id')

    # ### end Alembic commands ###
