"""empty message

Revision ID: 66be8f82d253
Revises: 5f284bd8e30b
Create Date: 2025-08-14 14:51:52.117145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66be8f82d253'
down_revision = '5f284bd8e30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.alter_column('trailer',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.alter_column('trailer',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
